# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 969dc6de8fc1a524a02e41ad4502b048ad8d490cfdd6a1c22153745a78caf9d4152b2a683d7dff8aa27e9686ba23eed291dc811cb27f32d7d77cda15e6f1fae4

test:
  secret_key_base: 5a12e98112564df5c9d80fa58fbf40e604ace75fe50f7320b779081b9d93a35f4d9eb70290b3dfbbbf78267891d597493650f5caa5525344a2361102a48494fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
